#!/bin/sh

case $1 in
dashboard)
    wget https://github.com/Dreamacro/clash-dashboard/archive/gh-pages.zip
    unzip gh-pages.zip
    rm -rf koolclash/webs/koolclash && mkdir -p koolclash/webs/koolclash
    cp -rf clash-dashboard-gh-pages/* koolclash/webs/koolclash
    rm -rf gh-pages.zip
    rm -rf clash-dashboard-gh-pages
    echo '----------------------------------------'
    echo 'Update to latest clash-dashboard'
    echo '----------------------------------------'
    ;;
pack)
    mkdir -p koolclash-build/koolclash
    cp -rf koolclash/* koolclash-build/koolclash

    cd koolclash-build

    upx=$(which upx)

    if [ "x$upx" != "x" ] && [ -x $upx ]; then
        upx ./koolclash/bin/*
    else
        echo '----------------------------------------'
        echo "You should install upx first!"
        echo '----------------------------------------'
        exit 1
    fi

    tar zcvf ../koolclash.tar.gz koolclash
    cd ..
    rm -rf koolclash-build
    echo '----------------------------------------'
    echo 'Build the latest version'
    echo '----------------------------------------'
    ;;
ipdb)
    wget https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz -O ipdb.tar.gz
    mkdir -p geolite
    tar zxvf ipdb.tar.gz -C geolite
    chmod 644 geolite/GeoLite2-Country_*/*
    cp -rf geolite/GeoLite2-Country_*/GeoLite2-Country.mmdb koolclash/koolclash/config/Country.mmdb
    rm -rf ipdb.tar.gz
    rm -rf geolite
    echo '----------------------------------------'
    echo 'Update the ipdb to latest'
    echo '----------------------------------------'
    ;;
*)
    echo '=================================================='
    echo '              KoolClash Build Tools'
    echo '--------------------------------------------------'
    echo 'Usage: build [option]'
    echo ''
    echo "dashboard\tUpdate clash-dashboard to latest"
    echo "ipdb\t\tUpdate GeoLite to latest"
    echo "pack\t\tBuild the package"
    echo '=================================================='
    ;;
esac
